// vm: argcv/cvars/ini, math/physics, occlusion/ray, level/stream/world, scene/graph, worker/task, ram/lerp, message/event/loop/frameskip
// dummy systems (plugins): audio, database, dev, gameplay, input, network, os, package, power, render, rpc/ipc, script, sysdir, vr, window...
